### ISSUE TITLE
Build on React Native error and run simulator from command line crashed

### ISSUE THREAD

**Issue by beiming** [airbnb/lottie-react-native#67]
Version

> react-native : 0.41.1
   lottie-react-native: 1.0.6
   lottie-ios: 1.0.2
   Xcode: 8.2.1

Install & Link follow by ReadMe

> npm i --save lottie-react-native
   react-native link lottie-ios
   react-native link lottie-react-native

Then run simulator: `react-native run-ios` build error:

    Undefined symbols for architecture i386:
      "_OBJC_CLASS_$_LOTStrokeShapeLayer", referenced from:
          _OBJC_CLASS_$_LOTCircleShapeLayer in libLottie.a(LOTEllipseShapeLayer.o)
          _OBJC_CLASS_$_LOTRoundRectLayer in libLottie.a(LOTRectShapeLayer.o)
          objc-class-ref in libLottie.a(LOTShapeLayerView.o)
      "_OBJC_METACLASS_$_LOTStrokeShapeLayer", referenced from:
          _OBJC_METACLASS_$_LOTCircleShapeLayer in libLottie.a(LOTEllipseShapeLayer.o)
          _OBJC_METACLASS_$_LOTRoundRectLayer in libLottie.a(LOTRectShapeLayer.o)
    ld: symbol(s) not found for architecture i386
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

    ** BUILD FAILED **

I searched same issues and solution [Cannot build on React Native 0.41.2 #59 ](https://github.com/airbnb/lottie-react-native/issues/59) add `Lottie.framwork` to App's Link Binary with Libraries. 

Now `react-native run-ios` build success,  install App OK. but crashed. use `react-native ios-log` 
    
    NOTE:  Most system logs have moved to a new logging system.  See log(1) for more information.
    Feb 17 14:58:20 xxxxxxs-MacBook-Pro CoreSimulatorBridge[28303] <Warning>: Got LSBundleProxy for 'com.xxxxxx.app', sequenceNumber 75, cacheGUID <__NSConcreteUUID 0x794620e0> 3D698A13-B724-46D7-A441-968CE563C13C
    Feb 17 14:58:20 xxxxxxs-MacBook-Pro assertiond[28299] <Error>: assertion failed: 16D32 13E233: assertiond + 16726 [1BD9E3D0-5485-3412-86B2-4BE50C825E80]: 0x1
    Feb 17 14:58:20 xxxxxxs-MacBook-Pro Unknown[28299] <Error>:
    Feb 17 14:58:20 xxxxxxs-MacBook-Pro CoreSimulatorBridge[28303] <Warning>: Launch successful for 'com.xxxxxx.app'
    Feb 17 14:58:20 xxxxxxs-MacBook-Pro com.apple.CoreSimulator.SimDevice.96E91E0D-6637-4C26-9947-8491B2EC7034.launchd_sim[28278] (UIKitApplication:com.xxxxxx.app[0xbad3][29456]) <Notice>: Service exited due to signal: Trace/BPT trap: 5
    Feb 17 14:58:20 xxxxxxs-MacBook-Pro SpringBoard[28295] <Warning>: Application 'UIKitApplication:com.xxxxxx.app[0xbad3]' crashed.
    Feb 17 14:58:20 xxxxxxs-MacBook-Pro assertiond[28299] <Error>: assertion failed: 16D32 13E233: assertiond + 16726 [1BD9E3D0-5485-3412-86B2-4BE50C825E80]: 0x1
    Feb 17 14:58:20 xxxxxxs-MacBook-Pro Unknown[28299] <Error>:
    Feb 17 14:58:20 xxxxxxs-MacBook-Pro SpringBoard[28295] <Warning>: Reply Error: Connection interrupted
    Feb 17 14:58:31 xxxxxxs-MacBook-Pro CoreSimulatorBridge[28303] <Warning>: Pasteboard change listener callback port <NSMachPort: 0x78e57ef0> registered

Click App icon again:

    Feb 17 14:59:06 xxxxxxs-MacBook-Pro assertiond[28299] <Error>: assertion failed: 16D32 13E233: assertiond + 16726 [1BD9E3D0-5485-3412-86B2-4BE50C825E80]: 0x1
    Feb 17 14:59:06 xxxxxxs-MacBook-Pro Unknown[28299] <Error>:
    Feb 17 14:59:06 xxxxxxs-MacBook-Pro com.apple.CoreSimulator.SimDevice.96E91E0D-6637-4C26-9947-8491B2EC7034.launchd_sim[28278] (UIKitApplication:com.xxxxxx.app[0xa1b2][29484]) <Notice>: Service exited due to signal: Trace/BPT trap: 5
    Feb 17 14:59:06 xxxxxxs-MacBook-Pro SpringBoard[28295] <Warning>: Application 'UIKitApplication:com.xxxxxx.app[0xa1b2]' crashed.
    Feb 17 14:59:06 xxxxxxs-MacBook-Pro assertiond[28299] <Error>: assertion failed: 16D32 13E233: assertiond + 16726 [1BD9E3D0-5485-3412-86B2-4BE50C825E80]: 0x1
    Feb 17 14:59:06 xxxxxxs-MacBook-Pro Unknown[28299] <Error>:
    Feb 17 14:59:07 xxxxxxs-MacBook-Pro SpringBoard[28295] <Warning>: Reply Error: Connection interrupted

And I find it can be run from Xcode, CMD+R, No Error. 

How can I run simulator from command line, Anyone can help me? thanks.

**Comment by indivisable** [comment]
See Step 6 here: https://github.com/airbnb/lottie-react-native/issues/31

Also add to **Embedded Binaries**

**Comment by huangbow** [comment]
If you talked about the example, actually, the problem is due to the pod lock file. You could go to example/ios, and run `pod update`. Then, you are good to go. I made a pull request about this. #60
