### ISSUE TITLE
Animations not showing on iOS

### ISSUE THREAD

**Issue by jncx** [airbnb/lottie-react-native#52]
Hi,

I've installed lottie-react-native and setup the code examples using the animation data, but it's just showing a blank screen and giving no error. Could you please let me know if I've missed any steps? (For example, do I need to install Lottie for iOS independently?)

Many thanks in advance for your help, and for the library, it looks awesome if I can get it up and running!

I ran:
    `npm install --save lottie-react-native`

then to meet the required deps:
    `npm install --save react-native@0.35`
    `npm install --save-dev babel-preset-airbnb`

Then, using the code from the docs, where path/to/animation.json is a valid path to the animation data copied from the example project:
```
import React from 'react';
import Animation from 'lottie-react-native';

export default class BasicExample extends React.Component {
  componentDidMount() {
    this.animation.play();
  }

  render() {
    return (
      <Animation
        ref={animation => { this.animation = animation; }}
        style={{
          width: 200,
          height: 200,
        }}
        source={require('../path/to/animation.json')}
      />
    );
  }
}
```

**Comment by baires** [comment]
Same boat here. I'm on `lottie-react-native 1.0.4` and the animation is not showing up. It was working on `lottie-react-native 1.0.1`.

**Comment by jjhesk** [comment]
@baires does it support core 0.41.0 now?

**Comment by baires** [comment]
@jjhesk Cant make it work with my stack

```
react-native-cli: 1.0.0
react-native: 0.41.2
```
At first I thought it was related to https://github.com/airbnb/lottie-ios/issues/86 but after manually pointing to new version of `lottie-ios` on my `podfile` same result, no animation. Its a shame I will have to look for another library.

**Comment by jjhesk** [comment]
yes. @lelandrichardson i got the similar error too. I am thinking if this library is usable still... i saw this at the console.

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_LOTStrokeShapeLayer", referenced from:
      _OBJC_CLASS_$_LOTCircleShapeLayer in libLottie.a(LOTEllipseShapeLayer.o)
      _OBJC_CLASS_$_LOTRoundRectLayer in libLottie.a(LOTRectShapeLayer.o)
      objc-class-ref in libLottie.a(LOTShapeLayerView.o)
  "_OBJC_METACLASS_$_LOTStrokeShapeLayer", referenced from:
      _OBJC_METACLASS_$_LOTCircleShapeLayer in libLottie.a(LOTEllipseShapeLayer.o)
      _OBJC_METACLASS_$_LOTRoundRectLayer in libLottie.a(LOTRectShapeLayer.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by indivisable** [comment]
Same here, it was working great with prior versions (build issues aside) but after I came back after a week or so it is not showing any animations. It build properly however using the code from example does not start animation, I'll try minimal example next.

Anyone have a solution for this? 

Lottie/Lottie RN: 1.0.6
RN: 0.38.0
iOS: 10.2.1 (Latest)

**Comment by indivisable** [comment]
@lelandrichardson Any ideas on this one? The project seems to be building correctly now however no animations are displaying. I'll see if I can dig in a bit deeper tonight and start debugging the render methods.

**Comment by aindong** [comment]
I'm also having this trouble right now. same version of lottie and react-native. First I was getting the version issues so I did `react-native upgrade` and now it compiles just fine and run w/o errors but also no animation

**Comment by leesolway** [comment]
Same issue.. Compiling, but no animation.. Just blank

**Comment by minhtc** [comment]
+1, no animation play

**Comment by mdramos** [comment]
Same here.

**Comment by GingerBear** [comment]
no animation playing on ios
react native 0.40.0

**Comment by g3r4n** [comment]
You have to remove LibLottie.a from linked iOS dependancies.

**Comment by GingerBear** [comment]
@g3r4n thanks, it works!

**Comment by vokhuyet** [comment]
@minhtc , could you tell me how to install lottie-react-native on android? i am trying with document but it have a issue "provided dependencies can only be jars. com.facebook.re
act:react-native:aar:0.42.0 is an Android Library"
thannks :)

**Comment by minhtc** [comment]
@vokhuyet 
Go to android/app/build.gradle, find the compileSdkVersion option inside of the android block and change it from 23 to 25

**Comment by vokhuyet** [comment]
@minhtc e làm thế rồi anh. cơ mà nó vẫn báo lỗi đó. e không hiểu sao lại thế(e viết tiếng việt được chứ ạ)

**Comment by minhtc** [comment]
@vokhuyet:
check this file: https://github.com/airbnb/lottie-react-native/blob/master/lib/android/build.gradle

change from:
provided "com.facebook.react:react-native:+"
to:
compile "com.facebook.react:react-native:+"

**Comment by vokhuyet** [comment]
@minhtc thank you very much. i will try :))

**Comment by vokhuyet** [comment]
@minhtc  thank you very much , it work

**Comment by mattk90** [comment]
In my case I had to add `libLottieReactNative.a` to Link Binary with Libraries under Build Phases. That solved it. It was somehow missing hmm
