### ISSUE TITLE
ios11 and xcode 9 have compilation errors

### ISSUE THREAD

**Issue by bdanis** [airbnb/lottie-react-native#198]
getting ARC semantic issues in my xcode project ever since updating to 9.0 and ios11

LotAnimationController.m - no visible interface for 'LotAnimationView' declares the selector 'convertRect:to LayerNamed:'
Lines 73 and 84 of LotAnimationController.m

**Comment by fossage** [comment]
@bdanis , what ended up being the solution to this?  I am hitting the same problem myself.

**Comment by bdanis** [comment]
Many things actually but the main issue was that xcode creates a cache of your code in your user /library/developer/xcode/derivedData
I noticed when i was clicking on the error in xcode. The file path was not the same. 
Try unlinking and removing the binary framework as well

From what i am reading, updating packages sometimes creates issues. There is a feature in RN that allows you to regenerate your ios and android projects
